/*
-- Query: select * from doctor_staff
LIMIT 0, 10000

-- Date: 2022-12-09 15:41
*/
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0055201040','Monte','Kender','mkender2i@tripadvisor.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0097782823','Lindy','Boddice','lboddice12@youku.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0201647249','Arlie','Cavy','acavy50@amazon.co.uk','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0354024434','Greggory','Falconar','gfalconar1a@51.la','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0436996634','Nahum','Learned','nlearned11@dedecms.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0547984227','Romy','Davidescu','rdavidescu2j@ft.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0558742432','Jecho','Melby','jmelby17@forbes.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0628291531','Neile','Fevier','nfevier4k@flavors.me','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0702318809','Quinn','Rothwell','qrothwell4h@ucsd.edu','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0706952154','Georg','Dommerque','gdommerque2w@examiner.com','Agender','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0725024240','Irvin','Penticost','ipenticost39@instagram.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0846389630','Yehudit','Wyson','ywyson2c@simplemachines.org','Male','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0851778879','Waylan','Brou','wbrou3s@nbcnews.com','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0883996448','Monah','Robertis','mrobertis58@aol.com','Female','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1055536051','Cale','Wollers','cwollers1f@goodreads.com','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1271551896','Kristine','Borth','kborth2x@marriott.com','Polygender','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1288928432','Wilmar','Izakoff','wizakoff15@weebly.com','Genderfluid','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1292099666','Ferdie','Bartoshevich','fbartoshevich36@hostgator.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1324065664','Carry','Durrell','cdurrellz@economist.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1356919634','Moselle','Teml','mteml3a@amazon.co.jp','Female','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1377022641','Rana','Teffrey','rteffrey1g@cbslocal.com','Female','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1455676721','Arney','Yuill','ayuill22@berkeley.edu','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1612382983','Joelly','Woolfall','jwoolfallw@usatoday.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1645302415','Earlie','Symmons','esymmonsv@51.la','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1736100564','Edythe','Winfred','ewinfred5@examiner.com','Female','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1758312297','Philip','Yakushkev','pyakushkev1e@sun.com','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1807115038','Grantham','Reay','greay59@parallels.com','Bigender','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1834524857','Gertrud','Ellwood','gellwood3t@slideshare.net','Female','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2045507416','Christos','Jevon','cjevon4l@baidu.com','Genderfluid','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2264768487','Allsun','Placide','aplacide38@mapy.cz','Female','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2273636563','Aggie','Tuny','atuny2l@utexas.edu','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2643636635','Kevina','Martill','kmartill1o@youku.com','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2709157314','Katusha','Popeley','kpopeley16@cbslocal.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2724915070','Ximenez','Bisset','xbisset3u@psu.edu','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2840821257','Dennison','Quan','dquan40@si.edu','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2898874752','Kora','Triggol','ktriggol30@whitehouse.gov','Female','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3043654978','Gasparo','Childrens','gchildrens4j@marketwatch.com','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3052688898','Marty','Rentcome','mrentcome46@walmart.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3089374498','Ada','Ramos','aramos2h@weebly.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3093041899','Trey','Hamilton','thamilton5a@rakuten.co.jp','Male','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3153308705','Durant','Cunnane','dcunnane44@imgur.com','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3348944074','Shaughn','Langthorne','slangthorne18@people.com.cn','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3406126200','Mannie','Bris','mbris4x@privacy.gov.au','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3516760206','Nehemiah','Ech','nech1u@house.gov','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3893073795','Zelma','Connew','zconnew1z@goo.ne.jp','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3925411941','Crystie','Byrne','cbyrne1n@sfgate.com','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3990307290','Stanfield','Ambrosoni','sambrosoni4@bigcartel.com','Male','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4075229238','Robinette','Davidowsky','rdavidowsky41@sfgate.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4127034610','Trent','Hillburn','thillburn1l@cornell.edu','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4333944554','Chicky','Swyre','cswyre2z@naver.com','Polygender','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4430778981','Menard','Binner','mbinner43@sciencedaily.com','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4527874373','Woodie','Keetch','wkeetch3k@artisteer.com','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4782013310','Nil','Winear','nwinear2y@t.co','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4811800680','Kaila','McEvon','kmcevon3b@wordpress.com','Polygender','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4868706578','Raffaello','Heinschke','rheinschke4g@wikipedia.org','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5007849804','Zora','Hardesty','zhardesty2b@php.net','Female','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5448917763','Quintin','Reddan','qreddans@statcounter.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5493028573','Brennen','Mattin','bmattin3@omniture.com','Male','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5673518099','Ryan','Abdee','rabdee1m@tripod.com','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5680138433','Bernardine','Chesters','bchesters4i@slashdot.org','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5969669466','Jillian','China','jchina3j@woothemes.com','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6141002722','Antons','Fridd','afridd1x@army.mil','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6237934332','Iggy','Kewish','ikewish1w@studiopress.com','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6310011235','Em','Witherup','ewitherup3c@posterous.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6455798074','Allen','Kivell','akivell2f@nba.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6491201023','Craggie','Brislawn','cbrislawn5g@sitemeter.com','Male','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6726995393','Otho','Pyatt','opyatt10@tinypic.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6737544509','Branden','Astell','bastell19@sourceforge.net','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6816536908','Agustin','Biagioni','abiagionix@yale.edu','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6877410629','Rollins','Norton','rnorton2e@reverbnation.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7027077205','Zedekiah','Koenraad','zkoenraad2d@ibm.com','Male','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7106265721','Abbey','Nary','anary13@ning.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7119032151','Alyssa','Deave','adeaveu@bloglines.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7233566526','Sephira','Denison','sdenison42@domainmarket.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7448126938','Jeffie','Collocott','jcollocott57@devhub.com','Male','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7476783409','Normie','Le Floch','nlefloch5f@nsw.gov.au','Bigender','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7516485306','Denver','Quinby','dquinby2k@tinyurl.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7520844668','Alisha','Stitwell','astitwell4m@ow.ly','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7585169108','Marilin','Mc Corley','mmccorley45@linkedin.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7780451755','Ilaire','Cortin','icortin37@noaa.gov','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7838280877','Judy','LaBastida','jlabastida47@miitbeian.gov.cn','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7885557790','Stern','Friedman','sfriedman1t@a8.net','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8380653815','Franklyn','Gawn','fgawn14@g.co','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8429001220','Lonnie','Sweetlove','lsweetlove4w@icq.com','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8516711498','Nanni','Preece','npreece4z@cnn.com','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8543135850','Emerson','Backhouse','ebackhouse2v@addthis.com','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8681952471','Suzette','Camfield','scamfield1v@abc.net.au','Genderfluid','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8701043048','Ellsworth','Rosengarten','erosengarten3r@rediff.com','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8831088378','Kevin','Tetley','ktetley3m@hhs.gov','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8847078962','Any','Enticott','aenticott3l@springer.com','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8882268373','Marylinda','Calan','mcalant@microsoft.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9048095786','Lotty','Jentin','ljentin21@google.ca','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9117226481','Scarface','Trosdall','strosdall4y@cocolog-nifty.com','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9473779968','Tatum','Popelay','tpopelayr@dropbox.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9569659874','Esmaria','Blackey','eblackeyy@nps.gov','Agender','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9663227303','Horatius','Pruckner','hpruckner20@hao123.com','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9706597808','Artemas','Carette','acarette1y@huffingtonpost.com','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9725132297','Adela','Dawidowitz','adawidowitz2g@sfgate.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9833336809','Melody','Pllu','mpllu2m@biblegateway.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9892546040','Thatch','Inglis','tinglis4n@ox.ac.uk','Male','Dantist');
