/*
-- Query: select * from medical_personal
LIMIT 0, 10000

-- Date: 2022-12-09 15:41
*/
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0055201040','Monte','Kender','mkender2i@tripadvisor.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0056249950','Nanice','Ackrill','nackrill3e@narod.ru','Genderqueer','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0097782823','Lindy','Boddice','lboddice12@youku.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0161806236','Moselle','Jado','mjado4p@ihg.com','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0201647249','Arlie','Cavy','acavy50@amazon.co.uk','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0268775176','Gonzales','Shayler','gshayler53@dot.gov','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0294184074','Bonnie','Towersey','btowersey2r@ibm.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0354024434','Greggory','Falconar','gfalconar1a@51.la','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0379670607','Merle','Cavie','mcavieq@theguardian.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0436996634','Nahum','Learned','nlearned11@dedecms.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0547984227','Romy','Davidescu','rdavidescu2j@ft.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0551094516','Cilka','Laffan','claffanc@vk.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0558742432','Jecho','Melby','jmelby17@forbes.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0628291531','Neile','Fevier','nfevier4k@flavors.me','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0653000332','Winfield','McElvogue','wmcelvogue1d@bloglines.com','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0653140231','Octavius','McGreary','omcgrearyo@shop-pro.jp','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0702318809','Quinn','Rothwell','qrothwell4h@ucsd.edu','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0706952154','Georg','Dommerque','gdommerque2w@examiner.com','Agender','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0719036941','Patrica','Lasseter','plasseter4u@senate.gov','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0725024240','Irvin','Penticost','ipenticost39@instagram.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0746219636','Coletta','Baggelley','cbaggelleyl@dropbox.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0846389630','Yehudit','Wyson','ywyson2c@simplemachines.org','Male','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0851778879','Waylan','Brou','wbrou3s@nbcnews.com','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0883996448','Monah','Robertis','mrobertis58@aol.com','Female','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0903688255','Siobhan','Carlisso','scarlisso4a@hibu.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('0997274026','Dov','Paulson','dpaulson4e@homestead.com','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1022229974','Bear','Common','bcommon5e@pcworld.com','Male','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1055536051','Cale','Wollers','cwollers1f@goodreads.com','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1255746858','Carey','O\'Downe','codownei@liveinternet.ru','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1271551896','Kristine','Borth','kborth2x@marriott.com','Polygender','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1288928432','Wilmar','Izakoff','wizakoff15@weebly.com','Genderfluid','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1292099666','Ferdie','Bartoshevich','fbartoshevich36@hostgator.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1324065664','Carry','Durrell','cdurrellz@economist.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1356919634','Moselle','Teml','mteml3a@amazon.co.jp','Female','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1377022641','Rana','Teffrey','rteffrey1g@cbslocal.com','Female','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1379177154','Edgardo','Frill','efrill28@si.edu','Male','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1455676721','Arney','Yuill','ayuill22@berkeley.edu','Male','SA');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1481121820','Bernice','Stebles','bstebles5h@loc.gov','Female','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1612382983','Joelly','Woolfall','jwoolfallw@usatoday.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1645302415','Earlie','Symmons','esymmonsv@51.la','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1685496717','Carey','Peasegod','cpeasegod4b@tiny.cc','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1736100564','Edythe','Winfred','ewinfred5@examiner.com','Female','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1758312297','Philip','Yakushkev','pyakushkev1e@sun.com','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1807115038','Grantham','Reay','greay59@parallels.com','Bigender','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('1834524857','Gertrud','Ellwood','gellwood3t@slideshare.net','Female','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2045507416','Christos','Jevon','cjevon4l@baidu.com','Genderfluid','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2055259334','Micheline','Sprowell','msprowell1j@upenn.edu','Genderfluid','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2107710090','Chlo','Burchfield','cburchfield2a@foxnews.com','Female','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2139154193','Wood','Furby','wfurby3x@bbc.co.uk','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2264126949','Martguerita','Donkersley','mdonkersley4s@facebook.com','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2264768487','Allsun','Placide','aplacide38@mapy.cz','Female','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2273636563','Aggie','Tuny','atuny2l@utexas.edu','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2280865858','Tam','Braisted','tbraisted3i@epa.gov','Genderqueer','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2295006481','Nicol','Bodill','nbodill3n@geocities.com','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2370372966','George','Feavearyear','gfeavearyear31@1und1.de','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2382153296','Rana','Vina','rvina4f@seesaa.net','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2388490669','Darby','Costellow','dcostellow5b@com.com','Female','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2487113448','Polly','Le Noir','plenoir1s@alexa.com','Female','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2643636635','Kevina','Martill','kmartill1o@youku.com','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2704909067','Genna','Fell','gfell56@springer.com','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2709157314','Katusha','Popeley','kpopeley16@cbslocal.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2710710145','Elsey','Spellworth','espellworth27@oakley.com','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2724915070','Ximenez','Bisset','xbisset3u@psu.edu','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2840821257','Dennison','Quan','dquan40@si.edu','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2864772876','Ephraim','Robelin','erobeling@icio.us','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('2898874752','Kora','Triggol','ktriggol30@whitehouse.gov','Female','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3043654978','Gasparo','Childrens','gchildrens4j@marketwatch.com','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3052688898','Marty','Rentcome','mrentcome46@walmart.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3089374498','Ada','Ramos','aramos2h@weebly.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3093041899','Trey','Hamilton','thamilton5a@rakuten.co.jp','Male','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3153308705','Durant','Cunnane','dcunnane44@imgur.com','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3232917445','Cosimo','Bagley','cbagley1b@amazon.co.uk','Non-binary','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3348944074','Shaughn','Langthorne','slangthorne18@people.com.cn','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3406126200','Mannie','Bris','mbris4x@privacy.gov.au','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3427453944','Tedie','Kernaghan','tkernaghan23@elegantthemes.com','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3468636776','Paddy','Luttger','pluttger1q@oaic.gov.au','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3516760206','Nehemiah','Ech','nech1u@house.gov','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3600741195','Arron','Ghidoni','aghidoni4t@stanford.edu','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3685370464','Layla','Lamberton','llamberton3p@privacy.gov.au','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3787322744','May','Balden','mbalden2u@nature.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3893073795','Zelma','Connew','zconnew1z@goo.ne.jp','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3925411941','Crystie','Byrne','cbyrne1n@sfgate.com','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('3990307290','Stanfield','Ambrosoni','sambrosoni4@bigcartel.com','Male','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4075229238','Robinette','Davidowsky','rdavidowsky41@sfgate.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4115462280','Georgeta','Fardy','gfardy49@prweb.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4118785757','Gay','Stegel','gstegel3q@so-net.ne.jp','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4127034610','Trent','Hillburn','thillburn1l@cornell.edu','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4188813601','Rycca','Jedrzejewski','rjedrzejewski1r@wikispaces.com','Female','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4221148454','Jean','Hullyer','jhullyer3g@amazonaws.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4333944554','Chicky','Swyre','cswyre2z@naver.com','Polygender','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4430778981','Menard','Binner','mbinner43@sciencedaily.com','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4527134612','Mordecai','Geill','mgeill4o@businessweek.com','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4527874373','Woodie','Keetch','wkeetch3k@artisteer.com','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4537311754','Anthony','Killwick','akillwickd@godaddy.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4559358486','Marsh','Christiensen','mchristiensen3w@bandcamp.com','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4580466039','Kiri','Greedier','kgreedier3d@google.com.br','Female','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4580487656','Myles','Colwill','mcolwill4d@opensource.org','Bigender','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4759667601','Hannis','Frantsev','hfrantsev5i@symantec.com','Female','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4782013310','Nil','Winear','nwinear2y@t.co','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4811800680','Kaila','McEvon','kmcevon3b@wordpress.com','Polygender','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4868706578','Raffaello','Heinschke','rheinschke4g@wikipedia.org','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4869279096','Dew','Bodicam','dbodicamm@unc.edu','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('4875746989','Guillaume','Swait','gswait5d@nationalgeographic.com','Male','Nmedical geneticsA');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5007849804','Zora','Hardesty','zhardesty2b@php.net','Female','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5068007927','Dredi','Lissemore','dlissemore4r@multiply.com','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5074866006','Merola','Anglin','manglink@desdev.cn','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5119963528','Chelsea','Mowlam','cmowlam26@shop-pro.jp','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5171517819','Rustie','Henryson','rhenryson5c@fastcompany.com','Polygender','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5200958245','Wallis','Ramlot','wramlotj@auda.org.au','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5321027528','Riane','Ruzic','rruzic2n@loc.gov','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5448917763','Quintin','Reddan','qreddans@statcounter.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5493028573','Brennen','Mattin','bmattin3@omniture.com','Male','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5516906326','Tresa','Fulcher','tfulcher48@army.mil','Non-binary','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5673518099','Ryan','Abdee','rabdee1m@tripod.com','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5680138433','Bernardine','Chesters','bchesters4i@slashdot.org','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5716326080','Tyrone','Botly','tbotly3h@geocities.jp','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5786771784','Peyton','Sommerling','psommerling3f@quantcast.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5899544902','Helaine','Saurat','hsauratb@cbsnews.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5920506016','Muffin','Cussons','mcussons1p@123-reg.co.uk','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5969669466','Jillian','China','jchina3j@woothemes.com','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('5986268431','Lydon','Dellenbrook','ldellenbrook8@ustream.tv','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6110796247','Flynn','Cruwys','fcruwys1c@instagram.com','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6141002722','Antons','Fridd','afridd1x@army.mil','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6178848269','Helli','Rawlin','hrawlin3y@github.io','Female','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6212674280','Gradeigh','Faint','gfaint55@state.gov','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6226574917','Carina','Pach','cpach2q@reddit.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6237934332','Iggy','Kewish','ikewish1w@studiopress.com','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6294539129','Robbert','Dugall','rdugall1h@ameblo.jp','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6310011235','Em','Witherup','ewitherup3c@posterous.com','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6455798074','Allen','Kivell','akivell2f@nba.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6491201023','Craggie','Brislawn','cbrislawn5g@sitemeter.com','Male','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6544574031','Constantia','Becerra','cbecerra4v@ask.com','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6599322662','Joeann','Grahamslaw','jgrahamslawf@mac.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6608722419','Melli','Yurkiewicz','myurkiewicz54@hubpages.com','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6634341524','Hester','Hursey','hhursey3v@opensource.org','Female','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6689282473','Lanae','Coleborn','lcoleborn24@goo.ne.jp','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6714027230','Gracie','Meiningen','gmeiningen29@kickstarter.com','Female','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6726995393','Otho','Pyatt','opyatt10@tinypic.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6737544509','Branden','Astell','bastell19@sourceforge.net','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6816536908','Agustin','Biagioni','abiagionix@yale.edu','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6877410629','Rollins','Norton','rnorton2e@reverbnation.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('6885923796','Belva','Kyncl','bkyncl5j@elpais.com','Female','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7027077205','Zedekiah','Koenraad','zkoenraad2d@ibm.com','Male','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7106265721','Abbey','Nary','anary13@ning.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7119032151','Alyssa','Deave','adeaveu@bloglines.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7142798815','Jaymie','Fearnyough','jfearnyough3z@cbslocal.com','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7165555226','Rosalynd','Hufton','rhufton1k@goodreads.com','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7194371235','Rowena','Ritmeier','rritmeier4q@comsenz.com','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7233566526','Sephira','Denison','sdenison42@domainmarket.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7285041041','Kay','Chesswas','kchesswas51@google.nl','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7286890751','Justino','Leathes','jleathes2s@exblog.jp','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7366545341','Constanta','Pottie','cpottie9@scientificamerican.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7385150705','Ash','Crassweller','acrassweller6@sciencedirect.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7410525908','Avril','Reitenbach','areitenbach2@dell.com','Female','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7448126938','Jeffie','Collocott','jcollocott57@devhub.com','Male','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7467423543','Kearney','Robertson','krobertsone@weebly.com','Non-binary','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7476783409','Normie','Le Floch','nlefloch5f@nsw.gov.au','Bigender','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7516485306','Denver','Quinby','dquinby2k@tinyurl.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7520844668','Alisha','Stitwell','astitwell4m@ow.ly','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7585169108','Marilin','Mc Corley','mmccorley45@linkedin.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7745324289','Lila','Eggers','leggers0@statcounter.com','Female','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7780451755','Ilaire','Cortin','icortin37@noaa.gov','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7838280877','Judy','LaBastida','jlabastida47@miitbeian.gov.cn','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7885557790','Stern','Friedman','sfriedman1t@a8.net','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7978329992','Lombard','Iacovides','liacovidesh@themeforest.net','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('7998720999','Ellette','Dotterill','edotterill33@parallels.com','Female','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8013930742','Powell','Isselee','pisselee32@irs.gov','Male','NA');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8016806821','Octavius','Durman','odurman34@tinypic.com','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8213344146','Winfred','Schwandner','wschwandner35@mapy.cz','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8295773917','Jorey','Boissier','jboissier2t@mapy.cz','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8380653815','Franklyn','Gawn','fgawn14@g.co','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8429001220','Lonnie','Sweetlove','lsweetlove4w@icq.com','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8430988645','Janis','Wall','jwall25@blogger.com','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8516711498','Nanni','Preece','npreece4z@cnn.com','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8543135850','Emerson','Backhouse','ebackhouse2v@addthis.com','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8614098227','Ad','Titford','atitfordn@dagondesign.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8663905033','Thoma','Foat','tfoat7@instagram.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8681952471','Suzette','Camfield','scamfield1v@abc.net.au','Genderfluid','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8701043048','Ellsworth','Rosengarten','erosengarten3r@rediff.com','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8831088378','Kevin','Tetley','ktetley3m@hhs.gov','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8847078962','Any','Enticott','aenticott3l@springer.com','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8850328737','Lucilia','Bertin','lbertin52@theatlantic.com','Female','NneurosurgeryA');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('8882268373','Marylinda','Calan','mcalant@microsoft.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9048095786','Lotty','Jentin','ljentin21@google.ca','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9117226481','Scarface','Trosdall','strosdall4y@cocolog-nifty.com','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9235913551','Clerc','Byforth','cbyforth2p@wp.com','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9441255386','Corinna','Thorley','cthorley4c@lycos.com','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9473779968','Tatum','Popelay','tpopelayr@dropbox.com','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9564492181','Loren','Trinbey','ltrinbey3o@e-recht24.de','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9569659874','Esmaria','Blackey','eblackeyy@nps.gov','Agender','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9663227303','Horatius','Pruckner','hpruckner20@hao123.com','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9706597808','Artemas','Carette','acarette1y@huffingtonpost.com','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9725132297','Adela','Dawidowitz','adawidowitz2g@sfgate.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9726954568','Meredeth','Spillman','mspillman1i@go.com','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9732774568','Cordie','Durbann','cdurbanna@ucla.edu','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9833336809','Melody','Pllu','mpllu2m@biblegateway.com','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9857352057','Randi','Yuryev','ryuryevp@woothemes.com','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9892546040','Thatch','Inglis','tinglis4n@ox.ac.uk','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9899540064','Sosanna','Roistone','sroistone1@time.com','Female','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`email`,`phone`,`specialty`) VALUES ('9949990785','Kaylil','Follan','kfollan2o@ftc.gov','Female','Pediatric');
