/*
-- Query: select * from nurse
LIMIT 0, 10000

-- Date: 2022-12-09 15:43
*/
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0134015142','Reinwald','Sansome','rsansome1x@howstuffworks.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0244295883','Rois','Yorkston','ryorkston12@soup.io','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0290197856','Genevieve','Monger','gmonger27@edublogs.org','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0686828933','Allina','Talboy','atalboy1g@qq.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0815177232','Winna','Trewett','wtrewett16@elpais.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0860627993','Anastasie','Bullus','abullus1v@bluehost.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0885259343','Cassie','Lyokhin','clyokhin2e@tumblr.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('0897735927','Conchita','Robertet','crobertets@sogou.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1425512887','Renie','Blakeway','rblakewayg@lulu.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1498376371','Edward','Le febre','elefebre6@pbs.org','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1516087216','Simeon','Callaway','scallaway7@shareasale.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1583530088','Lucila','Burchell','lburchelll@yolasite.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1627639217','Christan','Beebee','cbeebee21@intel.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1700880950','Farrand','De Laci','fdelaci2f@cam.ac.uk','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('1815917679','Raff','Pampling','rpamplingb@shutterfly.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2001029233','Gladi','Backshell','gbackshellh@about.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2017861170','Adela','Dudding','adudding1u@dropbox.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2032433648','Joli','McDougal','jmcdougal25@ca.gov','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2137575825','Barry','Macconaghy','bmacconaghy2a@multiply.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2238629343','Noelyn','Symmons','nsymmons2i@dedecms.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2387949358','Rivy','Joska','rjoska13@diigo.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2450405089','Darius','Bedinham','dbedinham1c@comcast.net','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2506280758','Kelsy','Sporton','ksportond@globo.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2547445913','Elston','Melrose','emelrose1i@vistaprint.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2593870494','Errol','Jirasek','ejirasek20@altervista.org','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2728272514','Dore','Eagleston','deagleston2b@imdb.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('2829889703','Oberon','Baldrick','obaldrick1d@blog.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3024612750','Brittne','Vondracek','bvondracek2d@skyrock.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3142267735','Cesaro','McKmurrie','cmckmurrie2j@studiopress.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3336125030','Gabriel','Voden','gvoden10@yale.edu','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3376844690','Udell','Patullo','upatullo1n@purevolume.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3439604616','Kim','Nudds','knudds1l@nydailynews.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3580867261','Ingelbert','Snowding','isnowding9@amazonaws.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3667179618','Myriam','Few','mfewn@livejournal.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3702012028','Mortie','Inston','minston1p@ameblo.jp','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3931303810','Marven','Hogbin','mhogbin1y@columbia.edu','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('3986161147','Dorella','Ruprich','druprich2o@independent.co.uk','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4000997467','Vachel','Belleny','vbelleny2l@sbwire.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4100904428','Jaimie','Faucherand','jfaucherand1k@gov.uk','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4121094301','Rubie','Rollings','rrollings23@imgur.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4171874750','Ximenez','Golda','xgoldar@hhs.gov','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4287135202','Reade','Utting','rutting18@wired.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4338975628','Glori','Dalling','gdalling2r@illinois.edu','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4362999787','Puff','Adamou','padamoup@youtu.be','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4447257211','Vivienne','Edes','vedes14@reuters.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4492923942','Noemi','Langworthy','nlangworthy1t@bloglovin.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4596219656','Hallsy','Smellie','hsmellie1b@mlb.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4896557441','Radcliffe','Raffels','rraffelsz@salon.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('4958372857','Tirrell','Gillmor','tgillmoro@usa.gov','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5042346848','Frannie','Drynan','fdrynan1e@typepad.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5050826292','Wayland','Weddell','wweddell11@xrea.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5092638885','Kristel','Witten','kwitten1q@phoca.cz','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5315461017','Halie','Puttnam','hputtnam8@wsj.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5325658948','Barret','Vogeller','bvogeller15@soundcloud.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5386603353','Cori','Markie','cmarkie24@blinklist.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5435192005','Misty','Sallis','msallisv@sitemeter.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5520300763','Rab','Pellitt','rpellitt22@webmd.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5576018877','George','Cayser','gcayser2n@oakley.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5615868783','Faythe','Scholtis','fscholtis28@usnews.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('5958845454','Reamonn','Trowl','rtrowl2c@newyorker.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('6432740622','Flor','Merwe','fmerwex@themeforest.net','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('6441372762','Fraser','Shevlan','fshevlan2g@vk.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('6500640330','Sharai','Miner','sminera@howstuffworks.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('6650924202','Robby','Fowlie','rfowlie1s@wikipedia.org','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('6827937704','Waylin','de Vaen','wdevaen1j@reddit.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7061319232','Joellen','Ferris','jferris1a@booking.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7063846590','Fayth','Trembath','ftrembathm@networksolutions.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7092141583','Dorie','De La Cote','ddelacotew@weibo.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7097503882','Emylee','McMackin','emcmackin2m@alibaba.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7246923136','Vinni','Warin','vwarint@chronoengine.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7339558977','Krisha','Garn','kgarn26@irs.gov','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7469684360','Edik','Ilewicz','eilewicz1o@amazonaws.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7517653873','Daniella','Casterton','dcasterton2p@photobucket.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7587008853','Tommy','Bayston','tbayston2@example.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7792566641','Irwin','Charte','icharte1f@bigcartel.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7815002943','Rebbecca','Lodge','rlodge0@wikipedia.org','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7875849063','Luisa','Arguile','larguiley@netlog.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('7892283846','Zebulon','Kirsch','zkirschk@facebook.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8024211688','Delmore','Yeskin','dyeskin19@networkadvertising.org','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8081633928','Fayette','Olivier','folivierf@walmart.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8085940620','Tomaso','Perceval','tperceval4@flickr.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8098530515','Fowler','Tarbett','ftarbett2q@comsenz.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8221600873','Cosette','Priestnall','cpriestnall1@bigcartel.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8326524719','Nonie','Rablen','nrablen1w@hud.gov','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8379778464','Gisele','Briars','gbriarsu@washingtonpost.com','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8454512934','Arie','Harken','aharkenj@homestead.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8644677918','Yule','Dressel','ydressel29@parallels.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('8991463916','Shelly','Piff','spiff17@msu.edu','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9085047463','Saul','Pitkeathly','spitkeathlyq@simplemachines.org','Paramedic');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9357219986','Margaretta','Isaq','misaq5@sciencedaily.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9502561465','Chester','Parcall','cparcalle@intel.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9511341642','Kaja','Purcer','kpurcer2h@4shared.com','X-ray');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9532277897','Lucille','Kender','lkender1h@nhs.uk','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9562509532','Marve','Went','mwent1m@istockphoto.com','General practice');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9597416603','Mario','Romanski','mromanski1r@mail.ru','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9599914236','Florentia','Perschke','fperschke1z@seattletimes.com','Laboratory assistant');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9724615286','Sheilah','Reyner','sreynerc@jugem.jp','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9734989421','Tani','Mannock','tmannock3@cnn.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9785363295','Nicolea','Arrighetti','narrighettii@arstechnica.com','Midwife');
INSERT INTO `` (`id`,`first_name`,`last_name`,`phone_number`,`rank_nurse`) VALUES ('9822052596','Natalee','Djakovic','ndjakovic2k@tuttocitta.it','X-ray');
