/*
-- Query: select * from patient
LIMIT 0, 10000

-- Date: 2022-12-09 15:42
*/
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (1,'Ebony','Champneys','(139) 1625146','Female','26797 Northwestern Crossing');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (2,'Patrizius','Ramsier','(586) 3906776','Male','07270 Lillian Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (3,'Mae','Sprosson','(766) 3515778','Female','29813 Trailsway Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (4,'Rhett','Klesl','(634) 8231588','Male','98299 Golf Course Place');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (5,'Aldous','Seefus','(981) 2217084','Male','92 Novick Way');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (6,'Rubi','Rodbourne','(989) 8380937','Female','21098 Elgar Road');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (7,'Rosanne','Bowry','(617) 3194925','Female','124 Harper Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (8,'Claiborne','Ledford','(403) 5577847','Male','81 Heath Trail');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (9,'Samara','Meran','(170) 5592441','Female','18862 Mitchell Park');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (10,'Beale','Wyrill','(925) 4456122','Male','6 Tennessee Terrace');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (11,'Germana','Jovanovic','(844) 3620847','Female','73 Del Sol Crossing');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (12,'Dorri','Dommett','(753) 6025058','Female','03427 Goodland Place');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (13,'Shirley','McCandless','(536) 2388039','Female','62307 Kennedy Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (14,'Diane','Skoyles','(235) 8097452','Female','088 Gerald Center');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (15,'Morlee','Yuryaev','(995) 4352007','Male','5 8th Lane');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (16,'Heindrick','Kinde','(634) 3579793','Male','330 Mesta Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (17,'Rriocard','Leonards','(394) 2232672','Male','728 Sheridan Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (18,'Clive','Fazan','(414) 2434180','Male','84682 Thackeray Lane');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (19,'Sheelah','Fedorski','(304) 6317990','Female','6 Division Lane');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (20,'Devora','Millership','(807) 4499167','Female','1 Valley Edge Alley');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (21,'Tersina','Hall','(832) 3663104','Female','537 Springview Street');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (22,'Gibby','Nason','(107) 6404713','Male','2 Acker Lane');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (23,'Bobby','Gringley','(525) 5650612','Male','77826 Sunbrook Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (24,'Bax','Harries','(460) 8289461','Male','4695 Utah Avenue');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (25,'Jarib','Jell','(168) 5205968','Male','6656 Drewry Terrace');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (26,'Brunhilda','Goodacre','(413) 8821204','Female','96 Upham Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (27,'Tammie','Mellody','(409) 3587214','Female','20814 Elka Drive');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (28,'Cassi','Goulbourn','(927) 4947310','Female','248 North Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (29,'Bel','Fearn','(305) 1149066','Non-binary','8453 Mcbride Circle');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (30,'Allayne','Chatteris','(539) 2593024','Bigender','426 Dennis Street');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (31,'Nettle','Mears','(648) 3527146','Female','778 Clarendon Hill');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (32,'Zachariah','Ryle','(115) 3840171','Male','550 Bultman Trail');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (33,'Kingsly','Kollasch','(145) 2467318','Male','19706 Elgar Terrace');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (34,'Irvin','Zanicchelli','(887) 5248535','Male','8 Maryland Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (35,'John','Jachimak','(485) 8784416','Male','2 Saint Paul Road');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (36,'Dietrich','Malin','(153) 9192777','Male','259 Menomonie Park');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (37,'Luisa','Iacomo','(493) 9380397','Female','699 Fuller Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (38,'Deeann','De Malchar','(274) 3215968','Female','74710 Melody Drive');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (39,'Welch','Innis','(563) 4349605','Male','9 Dakota Center');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (40,'Donaugh','Skocroft','(596) 3181629','Male','71 Burrows Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (41,'Philipa','Antoniak','(139) 6688262','Female','74 Messerschmidt Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (42,'Konstantin','Scholey','(537) 8758272','Male','42341 Thierer Circle');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (43,'Aubrey','Crosham','(588) 5897444','Male','590 Prentice Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (44,'Barny','Nilles','(398) 7910079','Male','9923 Cody Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (45,'Mirilla','Zarfat','(230) 5327051','Female','29098 Pawling Trail');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (46,'Brok','Antonsen','(871) 7588910','Male','337 Autumn Leaf Road');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (47,'Selie','Curson','(425) 8191039','Female','63 Green Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (48,'Regan','Paunton','(391) 7132072','Female','95722 Pleasure Way');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (49,'Ted','Mollison','(911) 4121130','Female','72289 Texas Street');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (50,'Tamarah','Gauson','(646) 9431013','Female','63 Sunfield Road');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (51,'Blane','Ecob','(960) 8105547','Male','7722 Porter Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (52,'Astrix','Broadfield','(997) 9379799','Female','44009 Grover Place');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (53,'Timothy','Qualtrough','(136) 7480530','Male','2678 Ridge Oak Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (54,'Webster','Gurry','(520) 4675462','Male','310 Bartillon Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (55,'Raff','Lethlay','(123) 7349943','Male','1996 Hayes Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (56,'Jeffry','Garbett','(141) 1485946','Male','76 Kedzie Crossing');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (57,'Seth','Whetnall','(661) 9563448','Male','0513 Beilfuss Pass');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (58,'Judon','Garwood','(105) 1890056','Male','4 Pawling Circle');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (59,'Flori','Marris','(742) 6506064','Female','7 1st Terrace');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (60,'Tracey','Cansdill','(149) 8939555','Male','91424 Eggendart Circle');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (61,'Evin','Annwyl','(932) 2050393','Male','318 Messerschmidt Avenue');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (62,'Flore','Cavee','(829) 1439859','Agender','4 East Hill');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (63,'Hobey','English','(955) 6806950','Male','0 Rowland Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (64,'Eustacia','Leward','(180) 4013845','Female','3 Nevada Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (65,'Carmelita','Grelka','(490) 4610806','Female','7389 Muir Alley');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (66,'Ludovika','Daffern','(712) 2062213','Genderqueer','096 Sommers Terrace');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (67,'Stace','Piers','(250) 2056040','Female','49505 Sommers Circle');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (68,'Skelly','Conti','(741) 5332490','Genderqueer','60963 Brentwood Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (69,'Brietta','Amy','(255) 3550234','Female','580 South Center');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (70,'Aloisia','Briztman','(401) 7175164','Female','9 Hollow Ridge Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (71,'Bertrando','Dawtrey','(143) 1926652','Male','4396 Division Street');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (72,'Blaire','Ianitti','(624) 2260816','Female','1047 Anzinger Hill');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (73,'Marybelle','Garnett','(349) 3584012','Female','42 Duke Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (74,'Ignatius','Bath','(737) 9816088','Male','3 Chinook Crossing');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (75,'Issi','Quadrio','(976) 8129771','Female','096 Walton Trail');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (76,'Jarad','Maciak','(810) 8039103','Male','188 Ramsey Place');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (77,'Cchaddie','Salla','(622) 4125022','Male','553 Hansons Crossing');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (78,'Chilton','Fisk','(434) 6178393','Male','71 Oriole Hill');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (79,'Tynan','Late','(599) 6332687','Male','273 Washington Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (80,'Verena','Askem','(185) 4296739','Female','73 Sutherland Center');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (81,'Kirk','Harry','(177) 8218978','Male','6 Kropf Lane');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (82,'Field','Dulton','(680) 4757083','Male','79730 Scoville Parkway');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (83,'Jenelle','Canlin','(428) 9254570','Female','22 Sachtjen Court');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (84,'Mildred','Levay','(916) 8695539','Female','4024 5th Alley');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (85,'Michell','Stiggles','(164) 8516711','Female','8737 Green Street');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (86,'Philis','Lambot','(785) 8092343','Female','4629 Springs Road');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (87,'Cordell','Ayrton','(290) 4083634','Male','2 Algoma Alley');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (88,'Temp','Nolan','(743) 6999343','Male','759 Lakewood Gardens Street');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (89,'Joby','Gorriessen','(689) 4378533','Female','789 Laurel Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (90,'Penrod','Brasier','(183) 1313280','Male','11 Kedzie Plaza');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (91,'Doug','Bunclark','(193) 4275016','Male','4580 Londonderry Trail');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (92,'Leann','Goodlet','(148) 8091200','Female','5888 Southridge Alley');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (93,'Taryn','Le Bosse','(705) 8449945','Female','29 Messerschmidt Junction');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (94,'Marlo','Cobon','(691) 3450813','Female','532 Judy Circle');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (95,'Karla','Conradie','(801) 9361625','Non-binary','56969 Stuart Terrace');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (96,'Coleen','Orpyne','(115) 7516908','Bigender','960 Sundown Way');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (97,'Carney','Behagg','(450) 4494954','Male','55 Prairie Rose Drive');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (98,'Dalston','Krysztofowicz','(999) 6594360','Male','52 Petterle Point');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (99,'Alfy','Arnoult','(969) 7846451','Male','7 Green Junction');
INSERT INTO `` (`IIN`,`first_name`,`last_name`,`phone_number`,`gender`,`address`) VALUES (100,'Konstanze','De la Feld','(255) 4294251','Female','34 Gerald Lane');
