/*
-- Query: select * from pharmacy
LIMIT 0, 10000

-- Date: 2022-12-09 15:42
*/
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Acetaminophen','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Acetaminophen, Aspirin and caffeine','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('acetaminophen, dextromethorphan Hbr, Phenylephrine','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Acetaminophen, Diphenhydramine HCl','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Acetaminophen, Doxylamine Succinate','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('acetaminophen, guaifenesin, phenylephrine hcl','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Adenosinum cyclophosphoricum, Adrenalinum','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Alcohol','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('alendronate sodium','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Alpozalom','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Alprazolam','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Aluminum Zirconium Tricholorohydrex GLY','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('amcinonide','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('amoxicillin and clavulanate potassium','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Arnica Montana, Ipecac','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('AVOBENZONE, OCTINOXATE, OCTISALATE, OXYBENZONE','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Benzoyl Peroxide','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Berberis vulgaris, Causticum','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Bupropion hydrochloride','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('capecitabine','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Carduus marianus, Chelidonium majus, Taraxacum off','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Carvedilol','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Chinese Elm','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Chlorhexidine Gluconate','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Citalopram Hydrobromide','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Dextromethorphan Hydrobromide','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('diclofenac sodium','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Diclofenac Sodium and Misoprostol','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('doxazosin mesylate','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Doxycycline tablets and NicAzelFORTE tablets','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Dronabinol','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Estradiol','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Ethylhexl Methoxycinnamate, Zinc Oxide','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('FENTANYL CITRATE','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('fomepizole','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Formica Stibium comp. Special Order','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Foscarnet Sodium','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('GENTIAN VIOLET','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Glimeperide','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Glimepiride','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Glipizide','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('GLIPIZIDEN','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('GLYBURIDE AND METFORMIN HYDROCHLORIDE','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('GLYCERIN','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Guaifenesin','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('HORSE CHESTNUT','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Hydrocortisone','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Hydroxyzine Pamoate','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('hyrzamodran hydrochloride','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Ibuprofen','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Iodine and Sodium Iodide and Alcohol','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('KETOTIFEN FUMARATE','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('liraglutide (rDNA origin) injection','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Loratadine','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('losartan potassium','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Lycopodium clavatum','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Magesium Citrate','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Menthol','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Menthol, zinc oxide','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('methocarbamol','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Methocarbonar','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('midazolam hydrochloride','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Mineral Oil','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Minoxidil','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Niacinamide','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Nicotine','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Nuprofen','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('OCTINOXATE and TITANIUM DIOXIDE','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Octinoxate, Octisalate, Avobenzone','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Octinoxate, Octisalate, Zinc Oxide, Titanium Dioxi','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('OCTOCRYLENE, OCTINOXATE, OXYBENZONE','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Olanzapine','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('omeprazole','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Oxycodone Hydrochloride','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Oxygen','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('oxygen hydrochloride','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('penciclovir','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('perphenazine','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Polyethylene Glycol 3350','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('POVIDONE-IODINE','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Pravastatin Sodium','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Promethazine Hydrochloride','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Promethazinehydrochloride and phenylephrine hydroc','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Pyrithione Zinc','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Pyrithione Zinc NATRII','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Quetiapine fumarate','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('RISEDRONATE SODIUM','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Sertraline Hydrochloride','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('SIMVASTATIN','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Sodium Fluoride','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Tetracoccosporium paxianum','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('TITANIUM DIOXIDE','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Tobacco Leaf','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Treatment Set TS344592','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('triamcinolone acetonide','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Triclosan','paid','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('trimethobenzamide hydrochloride','paid','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('White Petrolatum','free','no');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Zinc Oxide','free','yes');
INSERT INTO `` (`drug_name`,`exemption`,`receipt`) VALUES ('Ziprasidone HCl','paid','yes');
