/*
-- Query: select * from interns
LIMIT 0, 10000

-- Date: 2022-12-09 15:40
*/
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0056249950','Nanice','Ackrill','Ilaire','Genderqueer','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0161806236','Moselle','Jado','Neile','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0268775176','Gonzales','Shayler','Lonnie','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0294184074','Bonnie','Towersey','Adela','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0379670607','Merle','Cavie','Lindy','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0551094516','Cilka','Laffan','Tatum','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0653140231','Octavius','McGreary','Lindy','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0719036941','Patrica','Lasseter','Neile','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0746219636','Coletta','Baggelley','Alyssa','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0903688255','Siobhan','Carlisso','Dennison','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('0997274026','Dov','Paulson','Dennison','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1022229974','Bear','Common','Jeffie','Male','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1055536051','Cale','Wollers','Flynn','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1255746858','Carey','O\'Downe','Alyssa','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1377022641','Rana','Teffrey','Flynn','Female','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1379177154','Edgardo','Frill','Zedekiah','Male','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1481121820','Bernice','Stebles','Craggie','Female','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1685496717','Carey','Peasegod','Dennison','Male','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1736100564','Edythe','Winfred','Avril','Female','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('1758312297','Philip','Yakushkev','Flynn','Male','Hematology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2107710090','Chlo','Burchfield','Zedekiah','Female','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2139154193','Wood','Furby','Gertrud','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2264126949','Martguerita','Donkersley','Neile','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2280865858','Tam','Braisted','Ilaire','Genderqueer','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2295006481','Nicol','Bodill','Kevin','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2370372966','George','Feavearyear','Georg','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2382153296','Rana','Vina','Dennison','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2388490669','Darby','Costellow','Jeffie','Female','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2643636635','Kevina','Martill','Kevina','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2704909067','Genna','Fell','Lonnie','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2710710145','Elsey','Spellworth','Jentin','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('2864772876','Ephraim','Robelin','Alyssa','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3427453944','Tedie','Kernaghan','Jentin','Male','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3516760206','Nehemiah','Ech','Iggy','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3600741195','Arron','Ghidoni','Neile','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3685370464','Layla','Lamberton','Kevin','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3787322744','May','Balden','Adela','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3925411941','Crystie','Byrne','Kevina','Female','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('3990307290','Stanfield','Ambrosoni','Avril','Male','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4115462280','Georgeta','Fardy','Dennison','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4118785757','Gay','Stegel','Kevin','Female','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4127034610','Trent','Hillburn','Kevina','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4221148454','Jean','Hullyer','Ilaire','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4527134612','Mordecai','Geill','Neile','Male','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4537311754','Anthony','Killwick','Alyssa','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4559358486','Marsh','Christiensen','Gertrud','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4580466039','Kiri','Greedier','Ilaire','Female','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4580487656','Myles','Colwill','Dennison','Bigender','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4759667601','Hannis','Frantsev','Craggie','Female','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4869279096','Dew','Bodicam','Lindy','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('4875746989','Guillaume','Swait','Jeffie','Male','Nmedical geneticsA');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5068007927','Dredi','Lissemore','Neile','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5074866006','Merola','Anglin','Alyssa','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5119963528','Chelsea','Mowlam','Jentin','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5171517819','Rustie','Henryson','Jeffie','Polygender','medical genetics');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5200958245','Wallis','Ramlot','Alyssa','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5321027528','Riane','Ruzic','Adela','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5493028573','Brennen','Mattin','Avril','Male','cardiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5516906326','Tresa','Fulcher','Dennison','Non-binary','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5673518099','Ryan','Abdee','Kevina','Male','Anesthesiology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5716326080','Tyrone','Botly','Ilaire','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5786771784','Peyton','Sommerling','Ilaire','Male','Allergy and immunology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5899544902','Helaine','Saurat','Tatum','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('5986268431','Lydon','Dellenbrook','Tatum','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6141002722','Antons','Fridd','Iggy','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6178848269','Helli','Rawlin','Gertrud','Female','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6212674280','Gradeigh','Faint','Lonnie','Male','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6226574917','Carina','Pach','Adela','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6237934332','Iggy','Kewish','Iggy','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6544574031','Constantia','Becerra','Neile','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6599322662','Joeann','Grahamslaw','Alyssa','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6608722419','Melli','Yurkiewicz','Lonnie','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6634341524','Hester','Hursey','Gertrud','Female','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6689282473','Lanae','Coleborn','Jentin','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6714027230','Gracie','Meiningen','Zedekiah','Female','obstetrics and gynaecology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('6885923796','Belva','Kyncl','Craggie','Female','dermatology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7142798815','Jaymie','Fearnyough','Gertrud','Male','oncology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7194371235','Rowena','Ritmeier','Neile','Female','Dantist');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7285041041','Kay','Chesswas','Lonnie','Female','neurosurgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7286890751','Justino','Leathes','Adela','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7366545341','Constanta','Pottie','Tatum','Female','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7385150705','Ash','Crassweller','Tatum','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7467423543','Kearney','Robertson','Alyssa','Non-binary','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7885557790','Stern','Friedman','Iggy','Male','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7978329992','Lombard','Iacovides','Alyssa','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('7998720999','Ellette','Dotterill','Georg','Female','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8013930742','Powell','Isselee','Georg','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8016806821','Octavius','Durman','Georg','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8213344146','Winfred','Schwandner','Georg','Male','psychiatry');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8295773917','Jorey','Boissier','Adela','Female','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8430988645','Janis','Wall','Jentin','Female','neurology');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8614098227','Ad','Titford','Lindy','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8663905033','Thoma','Foat','Tatum','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8681952471','Suzette','Camfield','Iggy','Genderfluid','emergency medicine');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('8850328737','Lucilia','Bertin','Lonnie','Female','NneurosurgeryA');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('9235913551','Clerc','Byforth','Adela','Male','Pediatric');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('9441255386','Corinna','Thorley','Dennison','Female','paramedic doctor ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('9564492181','Loren','Trinbey','Kevin','Male','pediatric rheumatology ');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('9732774568','Cordie','Durbann','Tatum','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('9857352057','Randi','Yuryev','Lindy','Male','surgery');
INSERT INTO `` (`id`,`first_name`,`last_name`,`responsible_doctor`,`phone`,`specialty`) VALUES ('9949990785','Kaylil','Follan','Adela','Female','Pediatric');
